// Code generated by go-swagger; DO NOT EDIT.

package circuits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/psforne/netbox-client-go/netbox/models"
)

// CircuitsProviderNetworksBulkPartialUpdateReader is a Reader for the CircuitsProviderNetworksBulkPartialUpdate structure.
type CircuitsProviderNetworksBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CircuitsProviderNetworksBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCircuitsProviderNetworksBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCircuitsProviderNetworksBulkPartialUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCircuitsProviderNetworksBulkPartialUpdateOK creates a CircuitsProviderNetworksBulkPartialUpdateOK with default headers values
func NewCircuitsProviderNetworksBulkPartialUpdateOK() *CircuitsProviderNetworksBulkPartialUpdateOK {
	return &CircuitsProviderNetworksBulkPartialUpdateOK{}
}

/*
CircuitsProviderNetworksBulkPartialUpdateOK describes a response with status code 200, with default header values.

CircuitsProviderNetworksBulkPartialUpdateOK circuits provider networks bulk partial update o k
*/
type CircuitsProviderNetworksBulkPartialUpdateOK struct {
	Payload []*models.ProviderNetwork
}

// IsSuccess returns true when this circuits provider networks bulk partial update o k response has a 2xx status code
func (o *CircuitsProviderNetworksBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this circuits provider networks bulk partial update o k response has a 3xx status code
func (o *CircuitsProviderNetworksBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this circuits provider networks bulk partial update o k response has a 4xx status code
func (o *CircuitsProviderNetworksBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this circuits provider networks bulk partial update o k response has a 5xx status code
func (o *CircuitsProviderNetworksBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this circuits provider networks bulk partial update o k response a status code equal to that given
func (o *CircuitsProviderNetworksBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

func (o *CircuitsProviderNetworksBulkPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /circuits/provider-networks/][%d] circuitsProviderNetworksBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *CircuitsProviderNetworksBulkPartialUpdateOK) String() string {
	return fmt.Sprintf("[PATCH /circuits/provider-networks/][%d] circuitsProviderNetworksBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *CircuitsProviderNetworksBulkPartialUpdateOK) GetPayload() []*models.ProviderNetwork {
	return o.Payload
}

func (o *CircuitsProviderNetworksBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCircuitsProviderNetworksBulkPartialUpdateDefault creates a CircuitsProviderNetworksBulkPartialUpdateDefault with default headers values
func NewCircuitsProviderNetworksBulkPartialUpdateDefault(code int) *CircuitsProviderNetworksBulkPartialUpdateDefault {
	return &CircuitsProviderNetworksBulkPartialUpdateDefault{
		_statusCode: code,
	}
}

/*
CircuitsProviderNetworksBulkPartialUpdateDefault describes a response with status code -1, with default header values.

CircuitsProviderNetworksBulkPartialUpdateDefault circuits provider networks bulk partial update default
*/
type CircuitsProviderNetworksBulkPartialUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the circuits provider networks bulk partial update default response
func (o *CircuitsProviderNetworksBulkPartialUpdateDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this circuits provider networks bulk partial update default response has a 2xx status code
func (o *CircuitsProviderNetworksBulkPartialUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this circuits provider networks bulk partial update default response has a 3xx status code
func (o *CircuitsProviderNetworksBulkPartialUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this circuits provider networks bulk partial update default response has a 4xx status code
func (o *CircuitsProviderNetworksBulkPartialUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this circuits provider networks bulk partial update default response has a 5xx status code
func (o *CircuitsProviderNetworksBulkPartialUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this circuits provider networks bulk partial update default response a status code equal to that given
func (o *CircuitsProviderNetworksBulkPartialUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *CircuitsProviderNetworksBulkPartialUpdateDefault) Error() string {
	return fmt.Sprintf("[PATCH /circuits/provider-networks/][%d] circuits_provider-networks_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *CircuitsProviderNetworksBulkPartialUpdateDefault) String() string {
	return fmt.Sprintf("[PATCH /circuits/provider-networks/][%d] circuits_provider-networks_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *CircuitsProviderNetworksBulkPartialUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *CircuitsProviderNetworksBulkPartialUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
